name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: O365Auth.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build artifact
    - name: Build artifact
      run: dotnet publish O365Auth -r win-x64 -c Release /p:PublishSingleFile=true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        # Artifact name
        name: O365Auth
        path: O365Auth/bin/Release/net8.0-windows/win-x64/publish/*.exe
